<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>c4ef0fb5-9797-425f-b5e4-99fc1fd98d9c</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Carter" Version="8.2.1" />
		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.7.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
		<PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="8.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Ordering.Application\Ordering.Application.csproj" />
	  <ProjectReference Include="..\Ordering.Infrastructure\Ordering.Infrastructure.csproj" />
	</ItemGroup>

</Project>
